//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminOptions
    {
        public int id_Option { get; set; }
        public string Name_Option { get; set; }
        public Nullable<int> id_Value { get; set; }
    
        public virtual AdminOptionValue AdminOptionValue { get; set; }
    }
}
