//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class characteristic
    {
        public int id_characteristic { get; set; }
        public Nullable<int> id_goods { get; set; }
        public Nullable<int> id_Param { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> id_Value { get; set; }
    
        public virtual All_Characteristic All_Characteristic { get; set; }
        public virtual Value Value { get; set; }
        public virtual Product Product { get; set; }
    }
}
