//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id_Price { get; set; }
        public Nullable<int> id_Product { get; set; }
        public string Price1 { get; set; }
        public Nullable<bool> Sales { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
