//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id_Product { get; set; }
        public string NameProduct { get; set; }
        public Nullable<int> id_Type { get; set; }
        public string Price { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> id_Guarantee { get; set; }
        public Nullable<int> id_Manufacturer { get; set; }
    
        public virtual Guarantee Guarantee { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
    }
}
